In [17]:
import pandas as pd
from datetime import date

In [18]:
today = date.today()
formatted_date = today.strftime("%Y-%m-%d")

In [19]:
file_path = f'sheets/ai_jobs_captured_list_{formatted_date}.xlsx'
df=pd.read_excel(file_path)
df.head()

,회사,제목,경력,근무형태,학력,근무지역,링크
0,바카티오,Impact Junior,경력 무관,학력 무관,15727,NaN,https://zighang.com/recruitment/d35bca1d-6a14-...
1,Microsoft,Cloud & AI Solution Engineer - Data Platform,1~2년차,정규직,학사,서울,https://zighang.com/recruitment/75242627-2e2b-...
2,HD현대,2025년 하반기 신입 사원 채용,경력 무관,정규직,학사,서울,https://zighang.com/recruitment/4709a098-6595-...
3,LGAI연구원,Software Engineer Internship (Business Intelli...,경력 무관,체험형 인턴,학사석사,서울,https://zighang.com/recruitment/074d5010-7b30-...
4,롯데하이마트,2025년 9월 롯데 하이 마트 신입 사원 채용 I'M 전형,신입,정규직,학사,서울,https://zighang.com/recruitment/9b6a5e98-b91d-...

In [20]:
corp_list_path = 'sheets/corp_list.xlsx'
df_corpList = pd.read_excel(corp_list_path)
df_corpList.head()

          회사
0  Microsoft
1       HD현대
2    LGAI연구원
3     롯데하이마트
4         두산

In [21]:
df['회사'] = df['회사'].str.replace(' ', '', regex=False)
df_corpList['회사'] = df_corpList['회사'].str.replace(' ', '', regex=False)
df['회사'] = df['회사'].str.replace(r'\([^)]*\)', '', regex=True).str.strip()
df_corpList['회사'] = df_corpList['회사'].str.replace(r'\([^)]*\)', '', regex=True).str.strip()

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사      316 non-null    object
 1   제목      316 non-null    object
 2   경력      316 non-null    object
 3   근무형태    316 non-null    object
 4   학력      316 non-null    object
 5   근무지역    315 non-null    object
 6   링크      316 non-null    object
dtypes: object(7)
memory usage: 17.4+ KB

In [23]:
df_mod = df[df['회사'].isin(df_corpList['회사'])]
df_mod.reset_index(drop=True, inplace=True)
df_mod

,회사,제목,경력,근무형태,학력,근무지역,링크
0,Microsoft,Cloud & AI Solution Engineer - Data Platform,1~2년차,정규직,학사,서울,https://zighang.com/recruitment/75242627-2e2b-...
1,HD현대,2025년 하반기 신입 사원 채용,경력 무관,정규직,학사,서울,https://zighang.com/recruitment/4709a098-6595-...
2,LGAI연구원,Software Engineer Internship (Business Intelli...,경력 무관,체험형 인턴,학사석사,서울,https://zighang.com/recruitment/074d5010-7b30-...
3,롯데하이마트,2025년 9월 롯데 하이 마트 신입 사원 채용 I'M 전형,신입,정규직,학사,서울,https://zighang.com/recruitment/9b6a5e98-b91d-...
4,두산,2025년 하반기 (주) 두산 사업부문 채용 연계형 인턴 채용,신입,전환형 인턴정규직,학사,서울,https://zighang.com/recruitment/b41ffc48-956d-...
...,...,...,...,...,...,...,...
91,Welocalize,Korean Data Labeler,경력 무관,프리랜서,학력 무관,서울,https://zighang.com/recruitment/1889502f-5756-...
92,iM뱅크,iM 뱅크 인재 POOL 등록,1년차 이상,정규직,학력 무관,서울,https://zighang.com/recruitment/1560c139-8cd1-...
93,국토교통부항공교통본부,항공 교통 본부 통계 * 데이터 분석 분야 일반 임기제 공무원 경력 경쟁 채용 시험 공고,1년차 이상,계약직,학력 무관,대구,https://zighang.com/recruitment/93859ef6-a5c1-...
94,Welocalize,Korean to Katakana Digital Content Evaluation ...,경력 무관,프리랜서,학력 무관,서울,https://zighang.com/recruitment/7225a487-d1c9-...
95,우리은행,디지털 부문 전문직 인재 Pool 상시 등록 (AI / 빅 데이터 / UX - UI),경력 무관,정규직,학력 무관,서울,https://zighang.com/recruitment/67da9ee1-c698-...

In [24]:
output_filename = f'sheets/list_in_major_corp_{formatted_date}.xlsx'
df_mod.to_excel(output_filename, index=False)